### ISSUE TITLE
optlang not working with latest cplex 12.7.1

### ISSUE THREAD

**Issue by matthiaskoenig** [biosustain/optlang#95]
Hi all,
I just installed the latest cplex 12.7.1.
Somehow optlang does not work with it. Looks like some attributes changed on the Cplex object.
```
In [2]: import optlang
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-b90a99bbabb7> in <module>()
----> 1 import optlang

/usr/local/lib/python2.7/dist-packages/optlang/__init__.pyc in <module>()
     31 # Load classes from preferred solver interface
     32 if available_solvers['CPLEX']:
---> 33     from optlang.cplex_interface import Model, Variable, Constraint, Objective
     34 elif available_solvers["GUROBI"]:
     35     from optlang.gurobi_interface import Model, Variable, Constraint, Objective

/usr/local/lib/python2.7/dist-packages/optlang/cplex_interface.py in <module>()
    116 _CPLEX_STATUS_TO_STATUS = {}
    117 for status_name, optlang_status in _STATUS_MAP.items():
--> 118     cplex_status = getattr(cplex.Cplex.solution.status, status_name, None)
    119     if cplex_status is not None:
    120         _CPLEX_STATUS_TO_STATUS[cplex_status] = optlang_status

AttributeError: type object 'Cplex' has no attribute 'solution'
```

py2.7, linux x64, optlang 1.1.3

The best
Matthias

**Comment by matthiaskoenig** [comment]
Just forgot to mention:
Probably it is a good idea to handle the solver interface import in some try catch block, so that one can fall back to an alternative solver if some solver interface cannot be imported.
Currently the only way to use optlang/cobrapy is to uninstall cplex :/
Gurobi/cplex/mosek ... will continue changing their attributes, but it would be nice if I could work with glpk without the need to uninstall cplex.

**Comment by KristianJensen** [comment]
Hi. Thanks for reporting this. Incidentally both of these issues have already been fixed, and will be out with the next release :)

**Comment by matthiaskoenig** [comment]
Great. thanks a lot.
